### ISSUE TITLE
Windows ?

### ISSUE THREAD

**Issue by JacoFourie1** [chainq/mosquitto-p#2]
Hi. How do I get this to work on Windows? I copied the mosquitto.dll file from the mosquitto install on my Windows PC to the same folder as where the app lives but it does not seem to work.

**Comment by JacoFourie1** [comment]
OK I found the problem. mosquitto_loop_start does not start and run. How Do I get it to run? For now I call mosquitto_loop in a timer and it works but would like to keep the code the same between Windows and Linux.

**Comment by chainq** [comment]
The default Windows build of `mosquitto.dll` doesn't ship with threading enabled, because then it would also need to bundle `pthreads.dll`, and they wanted to avoid that. Note this is entirely the decision of `libmosquitto` authors, and has nothing to do with `mosquitto-p`. Therefore you need to run your own subthread where it calls the right networking loop functions regularly, and handles various states of the connection and reconnection. An example of it is in `mqttclass.pas`, in the `TMQTTConnection.Execute` function, [check here](https://github.com/chainq/mosquitto-p/blob/master/mqttclass.pas#L360). 

The alternative would be to not use the C API directly, but use the bundled `mqttclass.pas` unit, which wraps this to a Pascal thread and hence works on Windows the same as on other platforms. Another alternative would be to rebuild `mosquitto.dll` with threading enabled, then you can stick to the low-level API and expect the same subthreading behavior on Linux and Windows. Hope this helps.

**Comment by chainq** [comment]
Closing the issue as the questioner didn't answer, and no changes needed in `mosquitto-p`, as far as I'm concerned.

**Comment by JacoFourie1** [comment]
Hi, sorry was out for a bit. Yes you can close it. I got it working the same way as on linux using your object methods. Thanks a lot.
