### ISSUE TITLE
Reconnect Question

### ISSUE THREAD

**Issue by JacoFourie** [chainq/mosquitto-p#4]
Hi.

Should the OnConnect callback fire after a autoreconnect ?
I subscribe to the toppics in the OnConnect Callback if rc = 0. 
It seems that the onconnect does not fire after a connection is lost or the reconnection code does not work.
I wrote a little test app. I connect to the broker. Then I disable the network and enable it again. The program then does not reconnect by its self. 

I saw that some of my apps that use the library would stop receiving messages. This is when I discovered this issue. Or maybe I am not using it the correct way.

**Comment by JacoFourie** [comment]
OK I see you have to wait a while. Seems to reconnect now.

**Comment by chainq** [comment]
Even if you closed this issue, I'd like to comment, because there are a few things to consider. 

First, the reconnect mechanism in the class itself has a backoff feature. Which means, during an unsuccessful reconnect, it will use longer and longer periods to wait, before it tries again. This is to avoid bombing an overloaded broker or network link with reconnection attempts. This can be disabled by setting `reconnect_backoff` to false in the `TMQTTConfig` record. However, I'd advise against this, unless you've got a good reason to do this (for example, having the broker as a local on the same machine might be one).

The second delay typically comes from the host name resolution. Sadly, even if connecting to a DNS server (to convert from a host name to IP) seems like an instant, synchronous operation under good network conditions, it is not. It's quite a complex, asynchronous protocol, which can result in significant delays when the network or server conditions are bad. Even worse, `libc` (which `libmosquitto` uses), has only synchronous methods to resolve a hostname to an IP address. (see the `gethostbyname` class functions). Under bad network conditions, this only-takes-a-few-ms DNS resolution time can extend significantly and take several seconds, or even longer, and then the `libc` name resolving functions completely block the calling process/thread. To make it even worse, it's not even possible to define a custom timeout for these functions. This is why most applications which have to operate under difficult network conditions usually utilize an external name resolution library, which can work in an asynchronous fashion.

In theory, `mosquitto-p` could do the name resolution on its own, using another library, then always feed only an IP address to `libmosquitto`, and thus avoid these DNS resolution delays. However, I felt for a simple implementation it was out of scope. It can be added if it's really necessary - but it will come with additional dependencies, esp. on Unix systems, as there's really no standard library function to do this.

Of course, if the server's IP address can be guaranteed to be a single address and fixed and stable, the DNS resolution can be also done on startup, in the application code, then an IP address string can be set in `TMQTTConfig.hostname` instead of a hostname, which would eliminate unpredictable reconnection delays due to hostname resolution problems.

Hope this helps to clear up some confusion regarding unpredictable reconnection delays.

**Comment by JacoFourie** [comment]
OK thanks for the info. I use only IP addresses or may end up using "advice.local" if I do not know the IP as it will only be used on the local lan.
